### ISSUE TITLE
Suggestion: script should download specific supported version of Spotify, not latest

### ISSUE THREAD

**Issue by jerkstorecaller** [mrpond/BlockTheSpot#125]
Currently the script downloads the latest Spotify release. Which means as soon as development slows down or is halted, when Spotify release an update, it will stop working. It's a bit too "agile", this npm/Docker/everything-is-at-latest-or-doesnt-work is needlessly fragile.

The original BlockTheSpot by mater131 still works years after its last commit because it downloads a specific version of Spotify (1.1.4.something) instead of the latest. 

I recommend doing something similar. .

**Comment by rednek46** [comment]
This repo only deals with the Latest Spotify release.
So I kept BlockTheSpot.bat to download only the latest Spotify available.

I would like to add the latest supported Spotify by BlockTheSpot if I could know the cdn for every release.
And since the above step is long and I will need to bump the batch file each time Spotify releases an update, Its an unwanted idea. Also, mrpond patches latest spotify upon hours after release. So, this is unwanted.
