### ISSUE TITLE
Kaspersky detection

### ISSUE THREAD

**Issue by maks244** [mrpond/BlockTheSpot#129]
https://i.imgur.com/pHrHDKA.png

**Comment by rednek46** [comment]
Hey @maks244,
Kaspersky may have detected it as a virus since the script provides you a choice to uninstall Spotify Windows store app. Also it downloads the patch from GitHub. You can review the script yourself to see if there are any suspicious code as the code written there is pretty straightforward to understand. Also, Chrome_elf is already whitelisted by windows defender team. This may be a Kaspersky specific issue and I can assure you that its a false positive.

**Comment by mrpond** [comment]
@maks244 try submit false positive in Kaspersky app. it will fixed soon.
