### ISSUE TITLE
Small bug with shortcut

### ISSUE THREAD

**Issue by amd64fox** [mrpond/BlockTheSpot#145]
Does anyone have something like this ? If the client is installed via [BlockTheSpot.bat](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mrpond/BlockTheSpot/blob/master/BlockTheSpot.bat), then after the installation is complete, there is no spotify shortcut on the desktop, you need to go to the `%appdata%\Spotify` folder and create it yourself.

`Windows 10 Pro 20H2`
`BlockTheSpot 2021.3.25.33`

**Comment by rednek46** [comment]
It worked for me the last time I installed with it few days ago. Maybe its something with the Spotify Installer itself.
Since this maybe a minor bug related to the bat, I close this soon since its not related for bug tracking of BTS itself. 

If you still notice this issue, you can discuss it on the discord linked in the readme or use https://github.com/rednek46/BlockTheSpot/ to submit issues related to the BlockTheSpot.bat .

**Comment by amd64fox** [comment]
I checked separately the latest Spotify installer `1.1.56.595` , it works well. I will try to observe with newer versions.
