### ISSUE TITLE
Random Ads after song is end and want go to next songs

### ISSUE THREAD

**Issue by Nevahkrad** [mrpond/BlockTheSpot#152]
i use latest spotify and got random Ads when the song is end and want to go the next song

**Comment by rednek46** [comment]
Provide Spotify version.
Turn on logging in config.ini and upload log here.

**Comment by Nevahkrad** [comment]
i used spotify version 1.1.57.443.ga02a6c4.
i have turn on logging in config.ini now and there still have ads after song end.

[https://ibb.co/LSFMWKn](url)

**Comment by rednek46** [comment]
in the spotify folder, there will be a blockthespot.log file.
upload it here.

**Comment by Nevahkrad** [comment]
BlockTheSpot - Build date: Fri Jan  8 21:48:54 2021
Mhook_SetHook - getaddrinfo success!
BlockTheSpot - Build date: Fri Jan  8 21:48:54 2021
allowed - apresolve.spotify.com
allowed - login5.spotify.com
allowed - spclient.wg.spotify.comallowed - spclient.wg.spotify.com

allowed - gae-spclient.spotify.com
allowed - gae-dealer.spotify.com
blocked - www.googletagservices.com
allowed - api.spotify.com
allowed - heads4-ak-spotify-com.akamaized.net
blocked - platform-lookaside.fbsbx.com
allowed - api-partner.spotify.com

**Comment by ronny941** [comment]
i tried and no ads appeared i have the latest version of spotify and blockthespot

**Comment by ronny941** [comment]
on the other hand, the spotify home  "recently listened songs" they have a bug because once you close the program and reopen it, it doesn't remember the songs you have listened to and it doesn't counting anymore
when it is open the songs are counts them normally but when you close and reopen the songs was vanished
and when you close and reopen the program the songs and the playlist or the artist are displayed in the home of spotify
this are the problem as you can see the songs I have listening now are the ones that I have pointed out to you once reopened the program should remain saved
![canzoni ascoltate di recente](https://user-images.githubusercontent.com/32131958/115798658-0e692500-a3d7-11eb-9ec5-ea2e910ca99a.JPG)
 not saved

but when I close spotify this not happens and the songs are disappeared
![Canzoni che avevo ascoltato Sparite](https://user-images.githubusercontent.com/32131958/115798766-4d977600-a3d7-11eb-8d23-0377495fae9c.JPG)

**Comment by ronny941** [comment]
@rednek46 i apologize for bothering you 
but i wanted to make sure it wasn't a bug of blockthespot i'm sorry for that

**Comment by rednek46** [comment]
its ok @ronny941 . 😅

**Comment by Nevahkrad** [comment]
yeah and my problem still no fix lol xD i try reinstall still same

**Comment by rednek46** [comment]
@Nevahkrad for the time, you can swap into the old UI. Its sure to block ads.

**Comment by ecko-dev** [comment]
> Provide Spotify version.
> Turn on logging in config.ini and upload log here.

do I have to change 0 to 1?

**Comment by rednek46** [comment]
@ecko-dev yes.

**Comment by Nevahkrad** [comment]
@rednek46 yeah i have using old ui and now work 100% thanks

**Comment by rednek46** [comment]
Closing this issue as no one seems to have voice ads.

**Comment by erwinlagu** [comment]
Fix
