### ISSUE TITLE
[Request] Don't download anything if BlockTheSpot is already "installed"

### ISSUE THREAD

**Issue by Dyras** [mrpond/BlockTheSpot#197]
Hello! I wish to use the .bat file as a way to start Spotify. I think this would be very newbie friendly too! This would more easily be done if nothing was downloaded if the elf file, etc were detected in the correct folder. Also, if the CMD prompt closed automagically.

Thanks for a great project!

**Comment by Nuzair46** [comment]
1. The bat script is not meant to start Spotify, but to install BlockTheSpot.
2. Everytime Spotify updates, it removes the patch so it needs redownloading again. The script downloads the latest BlockTheSpot and since this repo is updated from time to time, it is absolutely necessary to do so. Also the script cleans up everything after it works, so there is no patch saved anywhere.

3. The script can throw certain errors depending on your system which are not avoidable, and to debug and understand these errors, we need to keep the CMD prompt to be closed, otherwise the CMD will close on error and we will not know what caused the issue or whether everything is patched right as it is needed.
