### ISSUE TITLE
Windows Defender - Threat found

### ISSUE THREAD

**Issue by Jarfeh** [mrpond/BlockTheSpot#20]
It doesn't immediately detect it, but usually after around 5 days, defender will detect chrome_elf.dll as Trojan:Win32/Fuery.C!cl and delete it, requiring me to reinstall it. Is it a false positive or is there something I'm missing?

**Comment by mrpond** [comment]
Hi, thanks for asking

It is false positive.
This project is open source, upload it to virus total doesn't help much
Since everyone can check the source code, how it block the ads
and even can compile it to chrome_elf.dll by yourself(using visuals studio 2019).

If you submit it to virus total,
Few days later try upload it again and click reanalyze.

![image](https://user-images.githubusercontent.com/18654771/75110319-4c49ac80-565f-11ea-9dba-4247ea710f00.png)

**Comment by mrpond** [comment]
Hi I contact windows defender team, here the fix in long term

> Analyst comments:
> 
> 
> We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.
> 
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"
> 
> Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
> 
> Thank you for contacting Microsoft.

**Comment by Jarfeh** [comment]
Thank you!
