### ISSUE TITLE
Mostly useless because Spotify auto-updates every other day

### ISSUE THREAD

**Issue by jerkstorecaller** [mrpond/BlockTheSpot#225]
Spotify seems to release updates several times of week. So you run BlockTheSpot, then the next day Spotify auto-updates, overwrites BlockTheSpot's changes, ads are back, user has to run download and run BlockTheSpot again. I've just had to reinstall BlockTheSpot twice in one week. And I barely use Spotify.

I suggest that BlockTheSpot disable Spotify auto-updating as part of its installation, as it is, it's useless.

**Comment by amd64fox** [comment]
@jerkstorecaller 

you can do it here

https://github.com/amd64fox/SpotX

**Comment by Scharfschutzen** [comment]
So I'd like to second what @jerkstorecaller said--Spotify seems to have caught onto BlockTheSpot and Auto-Updates, resetting files. I even tried setting chrome_elf.dll as read-only with an Administrator account and blocking access to it on my regular account--didn't seem to prevent the update from messing with that file.

I did run the .bat that @amd64fox suggested and it immediately removed the ads again. I will see how long it persists and obviously if they come back, I will note my findings. Thanks again for proving free ad-less listening.

P.S. I have a modded version of Spotify Lite.apk on my phone that used to allow me to play songs by choice, but recently they seemed to have blocked it so now I can only shuffle songs. Again, seems like they are catching on.

**Comment by Nuzair46** [comment]
Blocking updates is out of scope for this repo. But you are free to try various working methods if you prefer keeping an older version of Spotify. 

I personally think Spotify is having updates many times a week is because they are alpha testing their client. Maybe once it's done, we will see the updates being regular like old times. 

I will probably open a request in Spotify website asking them to have an option in the client to disable updates. I will link it here then.

**Comment by jerkstorecaller** [comment]
Is it really out of scope? What do you think is more important to your users, listening to ad-free music on Spotify, or running the latest version 1.1239871234987132987.43243 instead of yesterday's 1.1239871234987132987.43242? I'm launching Spotify twice a week and each time BlockTheSpot is broken and I have to manually repair it. It's almost less time-consuming to listen to the ads than to use this tool.

I'm switching to @amd64fox 's version since it blocks updates. If one day Spotify releases some new killer app feature only available in a new version, then I will manually update it. That's what users want. I'm surprised you don't agree.

**Comment by Davoleo** [comment]
@jerkstorecaller 
> I'm launching Spotify twice a week and each time BlockTheSpot is broken and I have to manually repair it. It's almost less time-consuming to listen to the ads than to use this tool.
Umh, no? audio ads last 15 seconds per ad and you listen to multiple of them each time so that time comparison is definetely wrong.
patching spotify every update takes less than 3 seconds if you use the batch file / use the powershell command, copying files manually (if you really wanted to do it that way) would take you less and less time when you get used to the process so I'll approximate it at about the duration of 1~2 audio ads, so I don't know what you're talking about.

Furthermore keeping an older version of software is never a good idea, the effort of the whole team behind this project is to support the latest spotify, automatically blocking updates is deceiving for the end user, since many just apply the patch right away without thinking about what it does.

One more note if you really wanted to downgrade a block block updates on the app there are many guides on how to do that, one of them I wrote in my gist [here](https://gist.github.com/Davoleo/de08de14934146847ef7fff070e4a04b#downgrading-the-desktop-app)
Just don't expect extensive support from this project since it targets the latest version of spotify, and please don't belittle the effort people like @mrpond and @Nuzair46 put into this to update it.

If you have any other argument on the time you're wasting to apply the patch, feel free to tell me, and I'll suggest a faster way to apply it
