### ISSUE TITLE
Can't Remove "Upgrade" Button and AD Placeholder

### ISSUE THREAD

**Issue by Aldrichyl** [mrpond/BlockTheSpot#230]
Hello ! So as a Spicetify user, when I tried installing BlockTheSpot throught that Invoke command line and after choosing Y for the removal of the upgrade button & AD Placeholder, I got multiple error messages and powershell just closed, Spotify started and nothing had changed. Tried screenshoting it but it just went really fast. 
Also I'm on the latest version tested with BlockTheSpot (1.1.68)
I did want to try using the other options of installing BlockTheSpot but they do not remove those anyway and also Kaspersky Total Security identify it as a Trojan and quickly deletes it.

**Comment by Daksh777** [comment]
It seems like your antivirus might have flagged them as a trojan and thus you got the errors because the script was trying to do operations on deleted files.
If you want to remove the upgrade button and ad place holder, you can disable your anti-virus or use https://github.com/daksh777/spotifynopremium (this is a Spicetify theme and since you're already a Spicetify user, you can use this or even combine with other themes)

**Comment by Aldrichyl** [comment]
Oh Thank you, I'll try this and get back to you.

**Comment by Aldrichyl** [comment]
It seems that this works, thank you ! Also about this SpotifyNoPremium theme, can I add extensions or customize the color.ini file myself or would that mess up the whole thing ?

**Comment by Daksh777** [comment]
Yes, you're free to add any custom apps and/or extensions and customize the `color.ini` file and it shouldn't be a problem at all.
You can just copy the contents of `user.css` of SpotifyNoPremoum if you want to combine it with another theme and paste it in the other theme's `user.css`
