### ISSUE TITLE
Request: Enable Fullscreen Mode Button

### ISSUE THREAD

**Issue by Sanrax** [mrpond/BlockTheSpot#268]
## Feature Request 
For free users, the fullscreen button in Spotify is missing and only enabled for Premium users. Would it be possible to patch the xpui.js file to enable the button in a similar manner to how the upgrade button and ad banner were removed?

**Comment by amd64fox** [comment]
In cases of removing a button and an advertising banner, it was necessary to find a place and fracture the code there so that the element would not be displayed, and with full-screen mode it is much more difficult, you need to be well versed in js to understand the inclusion logic.

I have tried it more than once, but my initial knowledge of JS is not enough.

Use [spicetify](https://github.com/khanhas/spicetify-cli/wiki/Extensions#full-app-display), they made a full-screen mode there long ago, which you can customize for yourself.

**Comment by amd64fox** [comment]
@Sanrax 
Managed to activate full screen mode. [More detailed here.](https://github.com/amd64fox/SpotX)
