### ISSUE TITLE
bat file stuck if launched as admin and updating spotify

### ISSUE THREAD

**Issue by Araxeus** [mrpond/BlockTheSpot#276]
When launching the .bat file with admin rights then spotify can't install and it result in the whole thing being stuck forever

![image](https://user-images.githubusercontent.com/78568641/143899853-6ba2dcf1-95ec-4c8a-a3b5-436e1b7dc250.png)

Possible solution:
place
https://github.com/mrpond/BlockTheSpot/blob/4c4a4b634cafb0089cb9d80a7adc3e8f9c84b1b5/install.ps1#L107-L149

inside a "not currently admin" conditional
```bash
$principal = new-object System.Security.Principal.WindowsPrincipal([System.Security.Principal.WindowsIdentity]::GetCurrent())
if ($principal.IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)
```

**Comment by amd64fox** [comment]
Do you have an idea how to lower the launch rights of `SpotifySetup` via PowerShell?

**Comment by KUTlime** [comment]
First of all, there is no easy way how lower the permission within PowerShell. This scenario is not supported by Win32 API, mostly because there is no such application which needs that, except Spotify.

Before I came to BlockTheSpot (👍🏿to @mrpond for his afford), I used my custom Spotify installer with ad blocking. Only working solution how bypass this problem was use task scheduler.

Second of all, please, please... Do not use `>$null 2>&1` and similar crap in PowerShell scripts. It is 2021 and we are way behind this. 🙏🏿 🙏🏿 🙏🏿

**Comment by Nuzair46** [comment]
@KUTlime you are welcome to do a PR fixing all the issues in the current script by using the most appropriate approach and coding practice. I'm currently not able to maintain the script because of being busy irl and I don't have good knowledge on ps scripting. The script is just following "If it ain't broke, don't fix it". If you can improve the script feel free to do so.

**Comment by KUTlime** [comment]
Hi @Nuzair46,

yes, I have it on my task since I found your repo, but I haven't had time for refactoring. I will do it before 2021-12-31.

**Comment by Nuzair46** [comment]
will be tracked in #278

**Comment by amd64fox** [comment]
> Do not use `>$null 2>&1` and similar crap in PowerShell scripts.

What is it anyway ? 😄

**Comment by KUTlime** [comment]
> 
> What is it anyway ? 😄
> 

Exactly. 🙂
