### ISSUE TITLE
Remove maximal version check from autoinstaller.

### ISSUE THREAD

**Issue by Nuzair46** [mrpond/BlockTheSpot#334]
Currently when the script is ran, it checks if the installed Spotify version is between the supported minimum and maximum versions. 

There is a flaw in this logic that causes Spotify to reinstall for users.
The problem is that when Spotify has kind of 2 channels for releasing their installers. One is through in app update (update channel), one is through SpotifyFullInstall.exe (install channel) (which BTS script uses).

The problem arises on the these conditions.
Spotify sometimes provides the latest Spotify through update channel, but at the same time install channel will still have older version. This causes a problem in our script.

Case: 
Consider latest Spotify version is 1.2 
In the update channel, it is 1.2. In the installer channel it is still 1.1.
User has version 1.1, they run BTS script.
BTS reads that user has 1.1 and tries to install latest Spotify 1.2.
Since BTS uses install channel, Spotify 1.1 gets reinstalled. and gets patched.
When user restarts PC, Spotify reinstalls 1.2 via update channel and removes BTS.

This is the problem I noted with many users using the latest script. 
We should also note that many countries recieve the update late, so versions can have issue.

Suggested approach, remove maximal version.
If user is using Spotify above the minimal supported version, `1.1.73.517`, then do not update.
If below, then ask user for update.
In this way we can avoid Spotify update issue.

@KUTlime
cc: @SammCheese, I think we can remove the skipUpdateCheck here as the user will be asked whether to update or not.

Please share your thoughts here.

tracks #330

**Comment by SammCheese** [comment]
Sounds good!

**Comment by KUTlime** [comment]
@Nuzair46 Kudos for clear, verbose an well articulated explanation. 

I will share my thought in upcoming days.

**Comment by KUTlime** [comment]
> User has version 1.1, they run BTS script.
> BTS reads that user has 1.1 and tries to install latest Spotify 1.2..

This two sentences are not correct, right? It should be

> User has version 1.2, they run BTS script.
> BTS reads that user has 1.2 and tries to install latest Spotify 1.1.

**Comment by KUTlime** [comment]
@Nuzair46 You updated my message, it is hard to respond. I wanted to point out that the scenario from you description
> In the update channel, it is 1.2. In the installer channel it is still 1.1.
> User has version 1.1, they run BTS script.
> BTS reads that user has 1.1 and tries to install latest Spotify 1.2.

should not happen if 1.1 is supported by BTS (_which probably is_). If a user has 1.1, the install script will detect 1.1 and will not force the update. 

We need to precisely address the problem here.

## Scenario 1

### Invariants

> BTS support: 1.1
> Install channel 1.1
> Update channel 1.2

A user had 1.1 & used Spotify update channel to update client to 1.2.

The update removed BTS. The user will try to use BTS which detects untargeted version, so the BTS script will **install 1.1 from install channel**, patch the client and user is in a loop of upgrades until the BTS install script is updated & the latest installation is shipped to the Spotify install channel.

### Worst case scenario
 The Spotify client will work 👍🏿, but a user has to use the BTS script after an update of Spotify client. 👎🏿

## Scenario 2

### Invariants

> BTS support: 1.1
> Install channel 1.2
> Update channel 1.2

A user had 1.1 & used Spotify update channel to update client to 1.2.

The update removed BTS. The user will try to use BTS which detects untargeted version, so the script will **install 1.2 from install channel** (_this could happen meanwhile the install channel is updated to 1.2 but the BTS install script not_). The script will patch the unsupported client.

### Worst case scenario

The script will patch an unsupported versions of Spotify client 👎🏿, a user will be forced to useless updates if the BTW script is used. 👎🏿

## Scenario 3

### Invariants

> BTS support: 1.1
> Install channel 1.2
> Update channel 1.2

A user has whatever version of Spotify client, but use the BTS script with `UpdateClient = true`.

The BTS script will **install 1.2 from install channel** (_or any unsupported version_), patch the unsupported client.

### Worst case scenario

The script will patch an unsupported versions of Spotify client 👎🏿.

## Scenario 4

### Invariants

> BTS support: 1.1
> Install channel 1.2
> Update channel 1.2

A user uses the BTS script to install the Spotify client out of the box

The BTS script will **install 1.2 from install channel** (_or any unsupported version_), patch the unsupported client.

### Worst case scenario

The script will patch an unsupported versions of Spotify client 👎🏿.

## Scenario 5 & 6 & 7

Same as 2 & 3 & 4, but BTS will not break anything in the Spotify client.

As you can see, this is very complex problem which should not be underestimated, should be well discussed, and well designed solution should be applied.

## Possible solutions

### Strategy - Remove max version check

Remove the check for maximal supported version.

### Strategy - Prevent Spotify client from being updated

We can disabled the Spotify client update functionality and update management will be partially under our control.

### Strategy - Complete control over update

We can disabled the Spotify client update functionality, store binary installation file in repo, install client from the binary installation in GitHub and have a full control over the update management.

### Solution matrix

| ⬇️Strategy/Scenario ➡️ | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 
| - | - | - | - | - | - | - | - |
| Remove Max version check | ❓ | ❌ | ❌ | ❌ | ✅ | ✅ | ✅ |
| Prevent update | ✅ | ✅ | ✅ | ❌ | ✅| ✅ | ✅ |
| Complete update control | ✅ | ✅ | ✅ | ✅ | ✅| ✅ | ✅ |

✅ - Resolved, or prevented.
❌ - Unresolved.
❓ - Resolved, but unclear result.

Please, share your thoughts.

**Comment by Nuzair46** [comment]
@KUTlime Sorry, I accidentally edited it from my phone. idk how it happened. will read through you explanation and get back.

**Comment by Nuzair46** [comment]
@KUTlime After going through your explanation, I think its best to remove the max supported version as the likelyhood of BTS not supporting the latest version is very low and by looking at the history of this repo, that only happened when Spotify changed something major with their client like the new UI. Other kind of unsupported client happens when Spotify adds a new ad domain which BTS will also need to be updated for, but this change never breaks the working of the App but instead certain ads show up.

We are strictly against preventing updates in this repo which makes it hard for using the 2nd and 3rd solutions.
Let me know your thoughts.

**Comment by KUTlime** [comment]
> We are strictly against preventing updates in this repo...

@Nuzair46 This practically removes these options from the table. I will prepare the update to remove the max version check.

**Comment by KUTlime** [comment]
BTW: @Nuzair46 Why are you against preventing Spotify client updates in this repo? I'm annoyed by them and I think I'm not only one.

**Comment by Nuzair46** [comment]
@KUTlime Spotify client updates are annoying. But more often they bring more good for the end user like security patches and new features. And since BTS most of the time supports the latest update, we prefer users to update the client and potentially stay safe from any exploits.

**Comment by KUTlime** [comment]
@Nuzair46 You know, before I came to this repo, I was using Spotify Client v1.0.0.84 for 2-3 years (?) and I never had a problem. In addition, when I see the latest Spotify client, I see no new feature or innovation what so ever. 🤷🏿‍♀️

**Comment by Nuzair46** [comment]
> @Nuzair46 You know, before I came to this repo, I was using Spotify Client v1.0.0.84 for 2-3 years (?) and I never had a problem. In addition, when I see the latest Spotify client, I see no new feature or innovation what so ever. 🤷🏿‍♀️

True, the problems never does happen. But its better to be safe than keeping the users locked on older versions. Also blocking updates for Spotify is easy so, its better for a user to do that their own incase they want to. Forcing users to stay on older version is a bad idea.

Also Spotify has a history of deploying bugged clients and staying updated is the best solution.
