### ISSUE TITLE
How to prevent auto update (:

### ISSUE THREAD

**Issue by H3lix-Fire** [mrpond/BlockTheSpot#346]
### Commands
```cmd
rmdir %localappdata%\Spotify\Update
mkdir %localappdata%\Spotify\Update
icacls %localappdata%\Spotify\Update /deny "%username%":D
icacls %localappdata%\Spotify\Update /deny "%username%":R
```

###### That's it folks, enjoy. (:

**Comment by Nuzair46** [comment]
We don't want to prevent updates as the patch usually supports the latest clients.

**Comment by H3lix-Fire** [comment]
> We don't want to prevent updates as the patch usually supports the latest clients.

Hmmm 🤔 In my experience, updating essentially removes the patch. Or at the very least, re-enables ads, which is not ideal. This could just be an issue with my machine, or something else going on, but that's typically what goes on with me. So I figured I'd share how to disable updates, incase others face the same issue.

**Comment by Nuzair46** [comment]
@H3lix-Fire updates removes the patch for everyone. But since the patch supports latest version more often, we just recommend users use the latest client as it contains security, features and bug fixes most times. Blocking updates is a personal preference that can be easily done with the above commands but we dont recommend it for the said reasons.
