### ISSUE TITLE
Latest Windows Defender removes the patch.

### ISSUE THREAD

**Issue by rednek46** [mrpond/BlockTheSpot#39]
Latest update signature definition 1.313.1268.0 seems to block the patch as threat. After the latest Defender update, Spotify never opened and that's when I noticed this.

**Comment by mrpond** [comment]
I'm already sent report to Windows Defender on this.
Let's see what they'll do, I keep issue open.

**Comment by MasicoreLord** [comment]
That's what I ended up having to do even after clearing the definitions cache and updating them manually.
Why does it seem like a false positive of some kind keeps reappearing?

**Comment by rednek46** [comment]
@mrpond I have tried a new code the allows the chrome_elf.dll threat. I will make a pull request later after testing this thoroughly.

**Comment by mrpond** [comment]
> That's what I ended up having to do even after clearing the definitions cache and updating them manually.
> Why does it seem like a false positive of some kind keeps reappearing?

The windows defender itself didn't detect it as virus anymore,
but the cloud engine.
If enable automatic sample submission (which is enable by default)
It will submit to the cloud for analysis, little privacy issue here.

I already reach out to them, I think due to COVID-19, not respond yet.

p.s. as I mention several times, this project is opensource. you can check the source
what it does under the hood. 

![image](https://user-images.githubusercontent.com/18654771/79622814-0a128800-8143-11ea-9341-1d9d16fecce1.png)

**Comment by rednek46** [comment]
@mrpond @MasicoreLord I have added a code that allows this threat as an additional [FIX] script [here](https://github.com/rednek46/BlockTheSpot/tree/detection) and also another one within the batch files is requested to pull.

**Comment by mrpond** [comment]
Hi, please try again I already fix it in 2020.04.21 release.

**Comment by rednek46** [comment]
@mrpond the latest windows defender Version: 1.315.271.0 keeps removing the chrome_elf.dll unless it allowed.
