### ISSUE TITLE
Stuck with the app!

### ISSUE THREAD

**Issue by Aasemoon** [mrpond/BlockTheSpot#47]
Hi there,

First, I apologise since this is not exactly a bug of BlockTheSpot, but this issue is making it impossible for me to use BlockTheSpot and I have no idea why it's happening or how to resolve it.

Recently, I have been unable to install the desktop version of Spotify!! I removed the app from my system, and did a fresh install using BlockTheSpot.bat. But when I try to run Spotify, there's only the app! Even the installation through BlockTheSpot ends up with the app! And then naturally the ads are not blocked at all.

When I try to install the desktop version myself, the same thing happens. I seem to automatically install the app, no matter what I do!

I'm using the latest version of BlockTheSpot, on Windows 10 Pro [build 18363].

Any ideas how this is happening? I would appreciate any tips!

Cheers!

**Comment by rednek46** [comment]
> Recently, I have been unable to install the desktop version of Spotify!! I removed the app from my system, and did a fresh install using BlockTheSpot.bat. But when I try to run Spotify, there's only the app! Even the installation through BlockTheSpot ends up with the app! And then naturally the ads are not blocked at all.
> 
Spotify Installer installs the app as soon as the setup is run. There is no options to customize during the installation.
Can you please elaborate "there's only the app!" , I don't get what you mean.

FYI, BlockTheSpot.bat installs latest Spotify, if no installation found . And it applies the patch on top of it. If you are seeing a normal Spotify installed after running the bat file, then there is a successful  installation. If there are still ads, it means that the BlockTheSpot adblocker hasn't installed correctly , most probably because your Antivirus might have prevented the download of the patches.
In that case allow "chrome_elf.dll" from quarantine section from your antivirus, also make sure the antivirus is upto date and run the bat file again. if that doesn't work, use the manual patch method given in the readme.

**Comment by Aasemoon** [comment]
Hi there,

I understand your confusion at what I'm describing, I can't quite understand how this is possible either. But I mean precisely what I'm saying.

For years, I have been using Spotify desktop, with BlockTheSpot, and I had no issues. I have never once installed the Spotify Windows Store [app] version. 

As of about a month ago, the Spotify desktop application seemed to simply disappear from my PC, and when I looked for it in my programs, there was only the Windows Store app. Since then, it doesn't matter what I do, every time I download the Spotify desktop installation file, after installation I somehow end up with the Windows Store app!! 

I did a complete uninstall and removed every trace of the Windows Store app from my system. And then I ran BlockTheSpot.bat, and yes since there was no installation detected, I was expecting that the Spotify desktop application would be installed and patched. 

Except this did not happen. I once again have the Windows Store app on my system. And it has not been patched, naturally. I am completely baffled and can't for the life of me understand how this is possible. I thought perhaps Spotify has gone ahead and replaced the desktop app completely with the Windows Store version [for Win 10 at least]. But oddly I still have the desktop version, with BlockTheSpot, working perfectly on another system with Win 10.... I simply don't get it.

Any ideas?

**Comment by rednek46** [comment]
This can't ever happen. Have you tried to verify that the Spotify you see is really from Windows Store, See if you can launch it from windows store.
Also after installation with BlockTheSpot.bat goto "C:/users/username/appdata/roaming/Spotify/" and see if the Spotify files are present along with chrome_elf.dll, If yes, try running it with the spotify.exe in that dir. If it runs without any issues, then its the right installation. 

I found this issue at Spotify support
> 
> The problem is that Spotifys installer detects that the store version has been installed at one point and auto migrates back to the store version if you install the desktop version.
> Its done this since the store version was first released. 
> Once installed its a massive pain to get rid of it, and the only way that has consistently worked is to.
> * uninstall store version of spotify
> * copy spotify install folder from another machine that has the desktop version of spotify installed (pref a win8+ machine)
> * and run spotify

If you haven't, Download spotify installer manually from the official site and install and manually patch. 

In the case you have tried uninstalling the Spotify from store, I'd say try creating a new user account.
Or else my best bet would be  clean windows installation. 

This Issue seems clearly related to Windows 10. Maybe you should try contacting Microsoft support.

FYI: The method of copying a previously installed folder to %appdata% might work. But you might still face the issue when spotify updates.

The BlockTheSpot.bat has a windows store spotify detection code in it. If it find any installation, it will ask you if you want the script to remove spotify windows store edition automatically.

Another thing that i won't recommend is to see if any registries related to windows store spotify exists in the system and removing it might solve the issue.

**Comment by Aasemoon** [comment]
Yes, I have verified that it's the Windows store app, no doubt in it.
I've tried almost all of what you are mentioning here, including removing whatever leftovers I could find in the registry, all to no avail. But I have not yet tried moving the installation folder from another machine. I will try this. 
Thanks a lot for your recommendations.

**Comment by Aasemoon** [comment]
So just a quick follow up / solution, in case anyone else runs into this problem.

In the end this is a Windows issue. Apparently at some point Spotify Windows Store version got included in the bloatware that comes with Windows updates. So you could end up with this problem even if you've never installed the Windows Store version by choice. And once that has been installed, somehow it becomes impossible to get rid of it and install the desktop version. Every installation gets automatically reverted to the Windows Store version.

What fixed the issue for me finally, was to use a freeware called Revo Uninstaller to remove every trace of the Windows Store Spotify. And then I was able to install the desktop version [and therefore BlockTheSpot] again. By the way I did try other uninstallers.... for whatever reason this was the only one that did a thorough enough job seemingly.

Cheers!
