### ISSUE TITLE
Spotify - Microsoft Store

### ISSUE THREAD

**Issue by IlyasDiker** [mrpond/BlockTheSpot#50]
Hello, 
I tested your're add-blocker on the latest version of Spotify from Microsoft store, & it's working like a charm, Thanks you. 👍

**Comment by rednek46** [comment]
@IlyasDiker sorry to break it to you, but this will never work with the Microsoft Store Spotify, since the store checks the file integrity everytime, and if it finds a modified file, it will just reinstall spotify. More over to apply the patch manually is a pain in the ass since you have to acquire the ownership of "windowsApps" folder and even then the above verification happens, preventing you from using this modified files. Incase you ran the BlockTheSpot.bat file it will ask you to remove the MS Store Spotify and install the Desktop version, you might've confused here. 

Unless you did something else other than those mentioned above (which wont work or is not a good patch) I will be gladly hear it. Let us know how you managed to do it.
