### ISSUE TITLE
Stopped working after a day.

### ISSUE THREAD

**Issue by Radiqnt** [mrpond/BlockTheSpot#500]
- [x] You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - [x] You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - [x] You uninstalled Spotify and just ran the patch
 - [x] You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.
 - [x] You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
 - [x] You enabled logging by editing config.ini `set log = 1`.
 - [x] Make sure whether an issue related yours is already open or not.
 - [x] Make sure you have completed everything in the above checklist.

I installed this yesterday and it worked fine but now it just doesn't. Reinstalled Spotify and BlockTheSpot multiple times but the Premium features are gone and the 'Explore Premium' button has returned. Rerunning BlockTheSpot.bat does nothing.

**Comment by enterv0id** [comment]
Unfortunately, the exact same happened here.

**Comment by jacobgawel** [comment]
Yup, same here

**Comment by Jetveil** [comment]
Seems like account has been blocked too. Can't log in neither web version, nor mobile: get "something went wrong" error. Same thing with new account - stopped working the next day after using this script and got the same error message. But before logging me off, the Spotify.exe has gone mad and ran at 20% CPU whitch happend for the first time.
Idk if this things are connected, but I feel desperate not to be able to login, for the first time since 2017
