### ISSUE TITLE
The Lyrics are not showing up 

### ISSUE THREAD

**Issue by AmizonHi** [mrpond/BlockTheSpot#533]
- [x] You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - [x] You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - [x] You uninstalled Spotify and just ran the patch
 - [x] You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.
 - [x] You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
 - [x] You enabled logging by editing config.ini `set log = 1`.
 - [x] Make sure whether an issue related yours is already open or not.
 - [x] Make sure you have completed everything in the above checklist.

## Note: 
- Antivirus detections are false positive. Please only open an issue if you find any vulnerability in the code. False reports will be closed without notice.
- If we find that you have opened an issue without following the troubleshooting above, the issue will be closed without notice.

**Comment by TheMage217** [comment]
Same

**Comment by JustMarkJr** [comment]
I've had this problem as well.

**Comment by parzival649** [comment]
yeah me too, how to solve it?

**Comment by Nuzair46** [comment]
They made lyrics premium only.

**Comment by CallumJThompson** [comment]
Lyrics have been made a [premium edition by Spotify](https://www.distractify.com/p/why-did-spotify-make-lyrics-premium), most probably because it's a popular feature so they feel the need to monetise everything.
Since the lyrics are grabbed through Musixmatch, it may be possible to circumvent this, but I'm unsure.
For now, here are some tools for seeing Spotify lyrics that you may want to use for the foreseeable future:

- **[sptlrx](https://github.com/raitonoberu/sptlrx)** (Linux, Windows, MacOS) - Synchronised lyrics in your terminal. It is still updated frequently.
- **[Versefy](https://versefy.app/)** (Windows Only) - Microsoft Store app. It hasn't been updated in a couple of years, but it has a nice, simple GUI and supports other music players, as well as manual search and uses multiple sites to grab lyrics.
- **[Lyrics in terminal](https://github.com/Jugran/lyrics-in-terminal)** (Linux Only) - Python curses application to view lyrics of current playing song in terminal. I haven't used this as I currently do not use Linux but it supports Spotify and local music players (VLC, MPD, etc.)

**Comment by Tramp-BHK** [comment]
can anyone solve this lyrics problem

**Comment by TheMage217** [comment]
@Tramp-BHK [Lyrics-plus](https://spicetify.app/docs/advanced-usage/custom-apps/#lyrics-plus) still works but may be displayed differently from normal lyrics, turn off compact from the settings when on the synced tab to get the normal style.

**Comment by Tramp-BHK** [comment]
> @Tramp-BHK [Lyrics-plus](https://spicetify.app/docs/advanced-usage/custom-apps/#lyrics-plus) still works but may be displayed differently from normal lyrics, turn off compact from the settings when on the synced tab to get as close as possible to the normal style.

can u plz guide me through this lyrics-plus thing, i am not familiar with it
and thank you for your reply

**Comment by TheMage217** [comment]
@Tramp-BHK The link directs to the instructions, just enter these into command prompt:
spicetify config custom_apps lyrics-plus
spicetify apply

**Comment by Tramp-BHK** [comment]
@TheMage217   thanks buddy, i already tried it and i think i lost benefits of block the spots because i saw an ad and another banner came in for the f1st time in several months.
hope it's still blocking ads

**Comment by CallumJThompson** [comment]
If that's happening, install block the spot again. The batch file to auto
install will update Spotify and such which should update the filters. I
have made the script run every Monday so it stays updated.

**Comment by Tramp-BHK** [comment]
ok bro i will reinstall it . and if smthg happens i will reach to you back
thanks

**Comment by iEatP0op7** [comment]
same, hopefully blockthespot updates and bypasses it

**Comment by DistrutPioneer** [comment]
Spotify has room temperature IQ

**Comment by Nuzair46** [comment]
We wont be adding lyrics in this repo. You can use Spicetify extensions mentioned by others in this issue like lyrics plus. Please check the readme as it mentions how to make BlockTheSpot work with spicetify installed. Closing this issue now.

**Comment by Nuzair46** [comment]
@CallumJThompson you dont have to update blockthespot anymore. We updated the code to auto update the patch. So its set and forget.

**Comment by wdjoh1302da** [comment]
> @CallumJThompson you dont have to update blockthespot anymore. We updated the code to auto update the patch. So its set and forget.

Will we have to disable updates still?
