### ISSUE TITLE
app not launching after latest patch

### ISSUE THREAD

**Issue by DoctorGnario** [mrpond/BlockTheSpot#546]
I noticed this morning that Spotify wasn't launching, so I went through the usual steps; uninstalled using the .bat, restarted my computer and launched the latest installer .bat, and the Spotify app itself still just won't start. It works fine just plain Spotify, but once I install this, it doesn't launch anymore. I turned logging on, but the file is empty. It was working fine for me on the 15th, that's when I used it last.

**Comment by Nuzair46** [comment]
@DoctorGnario can you provide more info? like Spotify version and please follow the bug template. Its there for a reason.

@yolilad Any idea why this is happening? Multiple people have reported this since last to updates

**Comment by Yolilad** [comment]
I’m not sure, but the problem might be due to incorrectly installed Runtime Libraries. I’ve tested on two different computers and encountered no errors. @DoctorGnario, if you wish, you can manually try the latest pull request I’ve published.

https://ci.appveyor.com/api/buildjobs/cir3el4duiej1emx/artifacts/chrome_elf.zip

**Comment by DoctorGnario** [comment]
> I’m not sure, but the problem might be due to incorrectly installed Runtime Libraries. I’ve tested on two different computers and encountered no errors. @DoctorGnario, if you wish, you can manually try the latest pull request I’ve published.
> 
> https://ci.appveyor.com/api/buildjobs/cir3el4duiej1emx/artifacts/chrome_elf.zip

works like a charm. thanks!
