### ISSUE TITLE
suggestion for new installer

### ISSUE THREAD

**Issue by xuac** [mrpond/BlockTheSpot#59]
There is no problem with the current installer and it works amazing.

Just wanted to suggest another method to install without manually installing the script. cuz if I were to do it manually, I would as well manually put the dll in the right place.

to install:
```powershell
iwr https://tools.maximousblk.now.sh/BlockTheSpot.ps1 | iex
```

to uninstall:
```powershell
$rm=$true; iwr https://tools.maximousblk.now.sh/BlockTheSpot.ps1 | iex
```

using powershell of course

not saying to use my script, but something similar

more info: [tools.maximousblk.now.sh/BlockTheSpot](https://tools.maximousblk.now.sh/BlockTheSpot)

**Comment by rednek46** [comment]
@xuac it is a good idea, but it has some issues.  
  
1. For non tech savvy people, it is a bit easier to just run the batch file rather than running commands in a shell.  
2. This site is outside of github, which may or may not have a threat.
      But the script running from external sites can be easily manipulated unlike Git where the user can see what code they are running on their system, So it definitely has a threat which can exploit others system by running a malicious code.  
  
 * ##### ps. This is just my opinion.

**Comment by xuac** [comment]
@rednek46 That script is actually hosted on github and that URL is just a redirect to that script.

the script: https://github.com/maximousblk/tools/blob/master/BlockTheSpot.ps1

You can use github's raw url but that gets pretty long. 

you can use it anyways tho

to install:
```powershell
iwr https://raw.githubusercontent.com/maximousblk/tools/master/BlockTheSpot.ps1 | iex
```

to uninstall:
```powershell
$rm=$true; iwr https://raw.githubusercontent.com/maximousblk/tools/master/BlockTheSpot.ps1 | iex
```

**Comment by rednek46** [comment]
@xuac since you are using my BlockTheSpot script, you could fork [this](https://github.com/rednek46/BlockThespot/) where you can use it for your work as I would be updating the script from time to time to fix issues with the code or add a new feature to it. I'd still need to have the Mrpond's Thailand Protest note and Author name in the script.     
  
 Also, for your new method, you could add it to the readme of my repo mentioned above which I'll then request a pull here.

You can contact me at the issue section [here](https://github.com/rednek46/BlockTheSpot).

**Comment by mrpond** [comment]
HI, official installtion script currently maintain by rednek46,
but you are free to submit alternative installation script into this repository too.

Just make sure you had time to support issue, and I keep it as long as it work/maintain.
