### ISSUE TITLE
Installer no longer installs desktop version

### ISSUE THREAD

**Issue by halian** [mrpond/BlockTheSpot#76]
**Important**
 - Make sure you use [latest spotify](https://www.spotify.com) before reporting a bug.
 - Make sure you use the [latest blockthespot](https://www.github.com/mrpond/BlockTheSpot/releases) before reporting a bug.
 - Make sure if blockthespot DLL got replaced after spotify update (important).

**Describe the bug**
The installer downloaded by BlockTheSpot no longer installs the desktop version of Spotify, only the Microsoft Store one. As such, BlockTheSpot is presently unusable.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Spotify Version: 1.1.43.700.g20acee0f
 - BlockTheSpot Product Version: N/A -- cannot install

**Additional context**
N/A

**Comment by rednek46** [comment]
@halian This is an issue due to Windows itself.
You may have used the Spotify Windows Store version before which can lead to this issue.
Even if you manually install Spotify Desktop, you will end up having the Store App. Currently I Don't Know any workarounds for this.  
Refer to [this](https://github.com/mrpond/BlockTheSpot/issues/47) Issue with the same problem.  
In the mean time I'll try to see if there is any workaround.

**Comment by rednek46** [comment]
Also this is the detailed issue reported at Spotify.  
This issue is not related to BlockTheSpot.  
https://community.spotify.com/t5/Desktop-Windows/Getting-the-regular-Spotify-not-the-Windows-10-Store-version/td-p/4797187

**Comment by rednek46** [comment]
@halian You can try using Revo Uninstaller to remove the Spotify Store version and try again.

**Comment by halian** [comment]
This appears to have worked, though of course a more permanent fix would be ideal.

**Comment by rednek46** [comment]
@halian Good to know it worked for you.  
The only permanent Fix can be done by Microsoft for not Automatically migrating the app files to Store.  
I don't think we could do anything on our own.
