### ISSUE TITLE
Latest release detected as a virus in Windows 10

### ISSUE THREAD

**Issue by junpeikun** [mrpond/BlockTheSpot#86]
**Describe the bug**
[Latest release](https://github.com/mrpond/BlockTheSpot/releases/tag/26)'s _chrome_elf.zip_ file detected as a virus by Windows Defender.

**Desktop:**
 - OS: Windows 10 (19042.630)
 - Spotify Version: 1.1.46.916.g416cacf1
 - BlockTheSpot Product Version: 0.51.0.0

**Additional context**
Windows Defender reports the following:
Trojan:Win32/CryptInject!ml

**Comment by rednek46** [comment]
@junpeikun It is a false positive.
Make sure you are using the latest Definitions.

**Comment by Yuyu** [comment]
@rednek46 It appears you are not using the latest definitions.
```
Antimalware Client Version: 4.18.2010.7
Engine Version: 1.1.17600.5
Antivirus Version: 1.327.1054.0
Antispyware Version: 1.327.1054.0
```
Interestingly, my Defender reports it as `Trojan:Script/Oneeva.A!ml`

**Comment by rednek46** [comment]
@Yuyu Lol.
I think I don't have the update available in my location yet.

**Comment by thetechguy-cpu** [comment]
Hi.
I'm also getting this too. How do I update windows security defenitions?

**Comment by rednek46** [comment]
@thetechguy-cpu just update windows 10. It should update the antivirus.

**Comment by rednek46** [comment]
@junpeikun @Yuyu @thetechguy-cpu I found out that the latest BTS version causes the Virus triggering. It is a false positive. And Until the time @mrpond fix this issue, you can use this older [release](https://github.com/mrpond/BlockTheSpot/releases/tag/2020.10.16.24). This was tested with the latest Spotify and Defender and works fine.

**Comment by S-Simon** [comment]
> And Until the time @mrpond fix this issue, you can use this older [release](https://github.com/mrpond/BlockTheSpot/releases/tag/2020.10.16.24). This was tested with the latest Spotify and Defender and works fine.

Still triggers the antivirus

**Comment by rednek46** [comment]
> That still triggers the antivirus
>
Try this [BlockTheSpot.bat](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/rednek46/BlockTheSpot/blob/update/BlockTheSpot.bat)

This Bat file only uses the current release I tested. So, it is not recommended for future use.
While running the bat, If it doesn't give any errors, it means its good to go.

**Comment by mrpond** [comment]
Hi, I can't reproduce it.
`Antimalware Client Version: 4.18.2010.7
Engine Version: 1.1.17600.5
Antivirus Version: 1.327.1134.0
Antispyware Version: 1.327.1134.0
`

![image](https://user-images.githubusercontent.com/18654771/99572566-6efacd00-2a07-11eb-93bd-540286f7bec7.png)
personally hurt to said this, but seem machine learning can't disguise it from malware
![image](https://user-images.githubusercontent.com/18654771/99573034-2263c180-2a08-11eb-84cb-057e1f3fb56e.png)
you can turn off automatic sample submission. 
(I'm personally turn this off due to privacy since I'm also work with NDA and some proprietary software)

![image](https://user-images.githubusercontent.com/18654771/99573152-4f17d900-2a08-11eb-8074-eecaab073ef1.png)

**Comment by junpeikun** [comment]
> Please try new release https://github.com/mrpond/BlockTheSpot/releases/tag/26FIX (Compile from my personal pc)

This doesn't trigger the detection on my PC which has the latest definitions.

**Comment by mrpond** [comment]
thanks for issue here. Reported both detected/undetected dll to Microsoft 
![image](https://user-images.githubusercontent.com/18654771/99577976-b042ab00-2a0e-11eb-871b-89aa98ecb8da.png)
